name: Generate terraform docs
on:
  - pull_request
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Render terraform docs and push changes back to PR 
        uses: terraform-docs/gh-actions@main 
        with: 
          recursive: "true"
          recursive-path: "modules"
          output-file: README.md # default "README.md"
          output-method: inject # default "inject"
          output-format: markdown table # default "markdown table"
          git-push: "true"


          
